# [DAS509] 3강. Python Pandas 기초

## Python 자료형

- **Tuple (튜플)**은 한번 할당되면 어떤 방식의 변경도 불가능한 자료형 (why need?)

In [1]:
tup = (4, 5, 6)
tup

(4, 5, 6)

* List (리스트)는 자료 값이나 사이즈를 변경할 수 있는 일반적인 자료형

In [2]:
a_list = [2,3,7, None]
a_list

[2, 3, 7, None]

* Dictionary (딕셔너리)는 가장 중요한 자료구조로, 키(keys)와 값(values)으로 연결되어 있는 구조

In [3]:
fruit = {1:'apple', 2:'banna'}
fruit

{1: 'apple', 2: 'banna'}

* Set (셋)는 집합에 관련된 것을 처리하기 위해 만든 자료형으로 중복을 허락하지 않는다.

In [5]:
A = {10, 20, 30}
A
B = {10, 40, 30, 40}
B

{10, 30, 40}

### Numpy 자료형

- 배열 (array): 빠르고 효율적인 벡터 연산을 위해 Numpy 라이브러리에서 사용되는 자료형

## Pandas

- Pandas는 빠르고 효율적인 데이터 분석을 위해 제공되는 파이썬 라이브러리

* conda와 pip install 함께 실행 시 error 뜰 수 있으므로, 본인의 환경을 확인하여 선택하여 실행.

In [4]:
!pip install pandas 
# install pandas library
# conda install pandas 
# using conda

import numpy as np
import pandas as pd

Requirement already satisfied: pandas in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas) (2.2.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas) (2025.1)
Requirement already satisfied: six>=1.5 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

### Pandas 자료형

- Series (시리즈)
    - 다양한 자료형을 담을 수 있는 1차원 배열

In [7]:
score = pd.Series([90,95,80,85])
score

0    90
1    95
2    80
3    85
dtype: int64

- DataFrame (데이터프레임)
    - 스프레드시트 형식의 자료 구조 (2차원 배열)
    - 행과 열에 대한 색인을 가짐 (행 - index / 열 - column)
    - 동일한 길이의 리스트를 담고 있는 Dictionary

In [5]:
data = {"state": ["Ohio", "Ohio", "Ohio", "Nevada", "Nevada", "Nevada"],
	      "year": [2000, 2001, 2002, 2001, 2002, 2003],
	      "pop": [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
df = pd.DataFrame(data)
df

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

- 데이터프레임의 기본적인 정보를 살펴보는 방법
    - df.shape: 데이터프레임의 (행, 열) 크기 확인
    - df.index / columns: 행 / 열의 이름을 출력
    - df.dtypes: 컬럼별 데이터 타입 출력
    - df.info(): 데이터프레임의 전반적인 정보 제공 (행과 열의 크기, 컬럼 명, 값의 자료형 등)
    - df.head() / df.tail(): 자료의 앞 / 뒤의 일부분만을 확인

- Index (색인)
    - 축의 레이블 등을 저장하는 객체
    - 색인은 변경이 불가능

In [7]:
labels = pd.Index(np.arange(3))
labels

obj = pd.Series(np.arange(3), index = ["a", "b", "c"])
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

## Pandas 핵심기능

### 1. 재색인 (Reindex)

- 새로운 색인에 적합하도록 객체를 생성하는 기능

In [8]:
frame = pd.DataFrame(np.arange(9).reshape((3,3)),
                     index = ["a", "c", "d"],
                     columns = ["Ohio", "Texas", "California"])
frame

   Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [11]:
# Reindexing Rows (default)
frame2 = frame.reindex(index = ["a", "c", "d", "d"])
frame2

   Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8
d     6      7           8

In [12]:
# Reindexing Columns
states = ["Texas", "Utah", "California"]
frame.reindex(columns = states)
# or equivalently
frame.reindex(states, axis = "columns")

   Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

### 2. 행과 열의 삭제 (Deletion)

- drop 함수

In [12]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index = ["Ohio", "Colorado", "Utah", "New York"],
                    columns = ["one", "two", "three", "four"])
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [13]:
# delete rows (equivalent code)
data.drop(index = ["Colorado", "Ohio"])

          one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [ ]:
# delete columns (equivalent codes)
data.drop(columns = ["two"])
data.drop("two", axis = 1)
data.drop("two", axis = "columns")

          one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

### 3. 색인 (Index)

- []를 통해 원하는 데이터를 선택할 수 있음

In [15]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=["Ohio", "Colorado", "Utah", "New York"],
                    columns=["one", "two", "three", "four"])
data
data["two"]
data[["three", "one"]]

          three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

* 슬라이싱(slicing)이나 조건문(Boolean 연산자)을 통해 원하는 데이터를 선택할 수 있음

In [17]:
data[:2] 
data[data["three"] > 5]

          one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

- 색인을 통해 위치 or 조건의 값을 손쉽게 바꿀 수 있음

In [18]:
data[data < 5] = 0

- []색인은 정수로 색인되어 있을 경우, 이것을 (정수색인이 있는 경우) 레이블로 인식할 수도 있고, 위치값으로 인식할 수도 있어, 혼선을 일으킬 수 있음
- .loc (레이블기준)과 iloc(위치기준) 을 사용하는 것이 보다 선호됨

In [19]:
# .loc 레이블 기반 색인
data.loc["Colorado"]
data.loc[["Colorado", "New York"]]
data.loc["Colorado", ["two", "three"]]
data.loc[:"Utah", "two"]

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int32

In [20]:
# .iloc: 위치 기반 색인
data.iloc[2]
data.iloc[[2, 1]]
data.iloc[2, [3, 0, 1]]
data.iloc[[1, 2], [3, 0, 1]]
data.iloc[:, :3][data.three > 5]

          one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

### 4. 산술연산 (Arithmetic)

- 서로다른 색인을 가지고 있는 객체간의 산술연산도 처리 가능

In [21]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list("bcd"),
                   index=["Ohio", "Texas", "Colorado"])
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list("bde"),
                   index=["Utah", "Ohio", "Texas", "Oregon"])
df1
df2

          b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [22]:
df1 + df2
df1.add(df2)

            b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

### 5. 함수 적용 (Apply)

- 데이터프레임의 각 행이나 열의 1차원 배열에 함수를 적용

In [16]:
frame = pd.DataFrame(np.random.standard_normal((4, 3)),
                     columns=list("bde"),
                     index=["Utah", "Ohio", "Texas", "Oregon"])
frame

# 새로운 함수 정의 (range)
def f1(x):
    return x.max() - x.min()

frame.apply(f1) # along the row
frame.apply(f1, axis = "columns") # along the column

Utah      2.142751
Ohio      2.959512
Texas     0.535108
Oregon    1.573832
dtype: float64

- map: 각원소에 적용할 수 있음

In [18]:
# 숫자 (floating number)를 문자열로 변환
def my_format(x):
    return f"{x:.2f}"

frame.map(my_format)

            b      d      e
Utah     0.80  -0.25   1.89
Ohio     2.13   0.41  -0.83
Texas   -0.61  -0.35  -0.08
Oregon  -0.16  -0.80  -1.73

### 6. 정렬 (Sort)

- 기본적으로 오름차순으로 정렬 (ascending 옵션을 통해 내림차순으로 변경 가능)
- sort_index: 인덱스에 따라 정렬

In [19]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)),
                     index=["three", "one"],
                     columns=["d", "a", "b", "c"])
frame
frame.sort_index()
frame.sort_index(axis="columns")
frame.sort_index(axis="columns", ascending=False)

       d  c  b  a
three  0  3  2  1
one    4  7  6  5

- sort_values: 값에 따라 정렬

In [21]:
obj = pd.Series([4, 7, -3, 2])
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

- 결측치가 있는 경우

In [20]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])
obj.sort_values()
obj.sort_values(na_position="first")

1    NaN
3    NaN
4   -3.0
5    2.0
0    4.0
2    7.0
dtype: float64

- 데이터프레임의 경우 정렬 기준을 정해야함

In [22]:
frame = pd.DataFrame({"b": [4, 7, -3, 2], "a": [0, 1, 0, 1]})
frame
frame.sort_values("b")
frame.sort_values(["a", "b"])

   b  a
2 -3  0
0  4  0
3  2  1
1  7  1

### 7. 순위 (Rank)

- 낮은 순으로, 동점은 평균으로 처리하는 것이 기본값

In [23]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])
obj.sort_values()
obj.sort_values(na_position="first")

1    NaN
3    NaN
4   -3.0
5    2.0
0    4.0
2    7.0
dtype: float64

- 데이터프레임의 경우 각각 행과 열을 기준으로 모두 순위를 정할 수 있음

In [28]:
frame = pd.DataFrame({"b": [4.3, 7, -3, 2], "a": [0, 1, 0, 1],
                      "c": [-2, 5, 8, -2.5]})
print(frame)
print(frame.rank(axis = "columns"))

     b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5
     b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

# 데이터 로딩

- 판다스는 다양한 파일 포맷을 읽어올 수 있음.

### CSV 파일 읽어들이는 방법

- 가장 대표적인 파일 타입은 csv (Comma separated values)
- pandas.read_csv()함수의 옵션은 현재 50개가 넘음. 보다 자세한 내용은 공식 문서 참조(https://pandas.pydata.org/docs)
- 가장 기본적인 형태는 다음과 같음

- 가장 기본적인 형태는 다음과 같음

In [29]:
df = pd.read_csv("./examples/ex1.csv")
df

   a   b   c   d  message
0  1   2   3   4    Hello
1  5   6   7   8    World
2  9  10  11  12  Example

- Header가 없는 경우 (자동으로 생성)

In [30]:
pd.read_csv("./examples/ex2.csv", header = None)

   0   1   2   3        4
0  1   2   3   4    Hello
1  5   6   7   8    World
2  9  10  11  12  Example

- Header가 없는 경우 (직접 생성하는 경우)

In [31]:
pd.read_csv("./examples/ex2.csv", names=["a", "b", "c", "d", "message"])

   a   b   c   d  message
0  1   2   3   4    Hello
1  5   6   7   8    World
2  9  10  11  12  Example

- 위의 예제에서 message 열을 index로 지정할 수 있음

In [32]:
names = ["a", "b", "c", "d", "message"]
pd.read_csv("./examples/ex2.csv", names=names, index_col="message")

         a   b   c   d
message
Hello    1   2   3   4
World    5   6   7   8
Example  9  10  11  12

- 공백으로 구분되어 진 경우

In [ ]:
result = pd.read_csv("./examples/ex3.csv", sep="\s+")
result

   1   2   3   4    Hello
0  5   6   7   8    World
1  9  10  11  12  Example

- 서두에 메타정보가 나와 있는 경우

In [33]:
pd.read_csv("./examples/ex4.csv", skiprows=[0, 2, 3])

           # File created on 2024-02-28
1 2  3  4                         Hello
5 6  7  8                         World
9 10 11 12                      Example

- 결측값이 있는 경우: 판다스는 공백뿐만 아니라, NA나 NULL과 같이 흔히 통용되는 문자를 결측값으로 인식

In [ ]:
result = pd.read_csv("./examples/ex5.csv")
result

    a     b     c   d  message
0   1   2.0   3.0   4    Hello
1   5   NaN   7.0   8    World
2   9  10.0   NaN  12  Example
3  11  12.0  13.0  14      NaN

- 인코딩 설정

In [34]:
df1 = pd.read_csv("./examples/score1.csv")
df2 = pd.read_csv("./examples/score2.csv") 
# df2 = pd.read_csv("examples/score2.csv", encoding = 'euc-kr') # when encoding error occurs
df1

      Name  Math  English  Science
0    Alice    90       85       95
1      Bob    80       78       82
2  Charlie    88       92       85

In [68]:
df2

    이름  수학  영어  과학
0  앨리스  90  85  95
1    밥  80  78  82
2   찰리  88  92  85

- read_csv 함수의 주요 인수 (input argument)

| 인수 | 설명 |
| --- | --- |
| path | 파일위치를 나타내는 문자열 |
| sep / delimiter | 필드를 구분하기 위해 사용할 문자나 Regular Expression |
| header | 열이름으로 사용할 행 번호, 없는 경우에는 None으로 지정가능 |
| index_col | 색인으로 사용할 열 번호나 이름 |
| skiprows | 파일을 시작부터 무시할 행 수 또는 행번호 |
| nrows | 읽어 들일 행의 개수 |
| na_values | NA값으로 처리할 값들의 목록 |
| keep_default_na | 기본 NA값 리스트를 사용할지 여부 (deault는 True) |
| encoding | 파일의 인코딩에 사용한 방법 설정 - 한글이 들어간 경우 주의 필요 |

### 파일의 크기가 큰 경우

- 파일의 크기가 지나치게 크면 한꺼번에 불러오거나 확인하는 것이 불편할 수 있음
- 출력을 위한 옵션 조정

In [35]:
# 최대 10개만 출력
pd.options.display.max_rows = 10
result = pd.read_csv("./examples/ex6.csv")
result

    id     name  age           city  salary
0    1    Alice   25       New York   55000
1    2      Bob   30    Los Angeles   62000
2    3  Charlie   22        Chicago   48000
3    4    David   35        Houston   70000
4    5      Eve   28  San Francisco   65000
..  ..      ...  ...            ...     ...
10  11      Kim   26        Atlanta   57000
11  12      Leo   32   Philadelphia   60000
12  13      Mia   24      San Diego   54000
13  14     Nick   36      Las Vegas   69000
14  15   Olivia   23       Portland   52000

[15 rows x 5 columns]

- 파일의 첫 몇행만 보고싶은 경우

In [36]:
pd.read_csv("./examples/ex6.csv", nrows=5)

   id     name  age           city  salary
0   1    Alice   25       New York   55000
1   2      Bob   30    Los Angeles   62000
2   3  Charlie   22        Chicago   48000
3   4    David   35        Houston   70000
4   5      Eve   28  San Francisco   65000

### 엑셀 데이터 불러오기

- pandas.ExcelFile 혹은 pandas.read_excel 함수를 통해 엑셀파일을 읽을 수 있음
- openpyxl과 xlrd 라이브러리 설치 필요

In [ ]:
!pip install openpyxl xlrd
# 라이브러리 설치
# conda의 경우 conda install openpyxl xlrd -y

xlsx = pd.ExcelFile("./examples/ex1.xlsx") # 파일경로전달
xlsx.sheet_names # sheet 이름 출력
xlsx.parse(sheet_name = "Sheet1") # 위에서 출력된 이름으로 지정

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting xlrd
  Downloading xlrd-2.0.1-py2.py3-none-any.whl.metadata (3.4 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading xlrd-2.0.1-py2.py3-none-any.whl (96 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: xlrd, et-xmlfile, openpyxl
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5 xlrd-2.0.1

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   22      Chicago

- 색인열이 존재하는 경우

In [38]:
xlsx.parse(sheet_name="Sheet1", index_col=0)

         Age         City
Name
Alice     25     New York
Bob       30  Los Angeles
Charlie   22      Chicago

- pandas.read_excel 함수를 이용하여 같은 작업 수행 가능

In [39]:
frame = pd.read_excel("./examples/ex1.xlsx", sheet_name="Sheet1")
frame

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   22      Chicago

- 엑셀파일로 내보내기

In [40]:
writer = pd.ExcelWriter("./examples/ex2.xlsx")
frame.to_excel(writer, "Sheet1")
writer.close()

# or equivalently

frame.to_excel("./examples/ex2.xlsx")

/var/folders/b7/0gvcv52x6731h2x6pyx6llkm0000gn/T/ipykernel_3666/3551674220.py:2: FutureWarning: Starting with pandas version 3.0 all arguments of to_excel except for the argument 'excel_writer' will be keyword-only.
  frame.to_excel(writer, "Sheet1")

### JSON 데이터 불러오기

- JSON (JavaScript Object Notation)도 널리 활용되는 파일의 형식

In [41]:
obj = """
{"name": "Wes",
 "cities_lived": ["Akron", "Nashville", "New York", "San Francisco"],
 "pet": null,
 "siblings": [{"name": "Scott", "age": 34, "hobbies": ["guitars", "soccer"]},
              {"name": "Katie", "age": 42, "hobbies": ["diving", "art"]}]
}
"""

- json 라이브러리를 활용
- json.loads()함수를 이용하여 JSON파일을 파이썬 객체로 변환할 수 있음

In [42]:
import json
result = json.loads(obj)
result

{'name': 'Wes',
 'cities_lived': ['Akron', 'Nashville', 'New York', 'San Francisco'],
 'pet': None,
 'siblings': [{'name': 'Scott', 'age': 34, 'hobbies': ['guitars', 'soccer']},
  {'name': 'Katie', 'age': 42, 'hobbies': ['diving', 'art']}]}

- 파이썬 객체를 DataFrame 등의 자료구조로 아래와 같이 바꿀 수 있음

In [43]:
siblings = pd.DataFrame(result["siblings"], columns=["name", "age"])
siblings

    name  age
0  Scott   34
1  Katie   42

- 판다스의 pandas.read.json()함수를 이용하면 JSON 파일의 배열에 담긴 각 객체를 표의 행으로 간주하여 데이터프레임으로 변환

In [47]:
!cat ./examples/example.json

{
    "name": "Wes",
    "cities_lived": ["Akron", "Nashville", "New York", "San Francisco"],
    "pet": null,
    "siblings": [
        {"name": "Scott", "age": 34, "hobbies": ["guitars", "soccer"]},
        {"name": "Katie", "age": 42, "hobbies": ["diving", "art"]}
    ]
}

In [48]:
data = pd.read_json("./examples/example.json")
data

ValueError: All arrays must be of the same length